### ISSUE TITLE
Not working since support for nodejs8.10 is removed by AWS

### ISSUE THREAD

**Issue by newUserForTesting** [aws-samples/amazon-cognito-facial-recognition-auth#1]
If possible could you please fix it?

Also while deploying manually AWS SAM CLI, facing following error:

>npm run bd

> cognito-facial-rekognition-auth-backend@1.0.0 bd C:\Users\saurabh\Downloads\amazon-cognito-facial-recognition-auth-master
> npm run check-env && npm run package && npm run deploy

> cognito-facial-rekognition-auth-backend@1.0.0 check-env C:\Users\saurabh\Downloads\amazon-cognito-facial-recognition-auth-master
> if [ -e ${S3_BUCKET_NAME} ] || [ -e ${USER_POOL_NAME} ] || [ -e ${STACK_NAME} ] || [ -e ${SES_FROM_ADDRESS} ]; then exit 1; fi

-e was unexpected at this time.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cognito-facial-rekognition-auth-backend@1.0.0 check-env: `if [ -e ${S3_BUCKET_NAME} ] || [ -e ${USER_POOL_NAME} ] || [ -e ${STACK_NAME} ] || [ -e ${SES_FROM_ADDRESS} ]; then exit 1; fi`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cognito-facial-rekognition-auth-backend@1.0.0 check-env script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\saurabh\AppData\Roaming\npm-cache\_logs\2020-01-08T04_59_37_910Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cognito-facial-rekognition-auth-backend@1.0.0 bd: `npm run check-env && npm run package && npm run deploy`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cognito-facial-rekognition-auth-backend@1.0.0 bd script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\saurabh\AppData\Roaming\npm-cache\_logs\2020-01-08T04_59_37_977Z-debug.log

**Comment by newUserForTesting** [comment]
Could someone please reply?

**Comment by newUserForTesting** [comment]
Hoping that somebody would have helped. sigh

**Comment by enr1c091** [comment]
Hi! Thank you for pointing this error and sorry for the late response! 

I'll be fixing the runtimes and committing the code.

**Comment by enr1c091** [comment]
Hopefully it's working now. Closing this issue for now :)

**Comment by ulisescarreonalvarez** [comment]
I got the same error
